[package]
name = "otel-arrow-proto"
version = "0.1.0"
edition = "2021"

[features]
default = ["full"]
full = ["client", "server", "trace"]
client = []
server = []
trace = []

[dependencies]
prost = "0.13"
tonic = "0.12"

[build-dependencies]
tonic-build = "0.12"
